name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

  # Allow triggering this workflow from another repo to update the docs after a release
  repository_dispatch:

jobs:
  all:
    name: all
    runs-on: ubuntu-latest
    # An explicit environment reference is needed to access environment secrets
    environment: ${{ github.ref == 'refs/heads/main' && 'foxglove-docs (Production)' || 'foxglove-docs (Preview)' }}

    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - run: yarn install --immutable

      - run: yarn run tsc
      - run: yarn run lint:ci

      - run: yarn run build
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          POSTHOG_KEY: ${{ secrets.POSTHOG_KEY }}

      - name: Deploy
        uses: cloudflare/pages-action@v1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          gitHubToken: ${{ github.token }}
          branch: ${{ github.head_ref || github.ref_name }}
          projectName: foxglove-docs
          directory: build
